### ISSUE TITLE
Get scripts working

### ISSUE THREAD

**Issue by samfalconer** [Tour-de-Force/btc-infrastructure#1]
There are some things that depend on Python 2, yet the default Windows Server 2012 RC don't have it.

We need to automatically install Python 2 and set the PYTHON environment variable to the path of the Python exe.

EDIT: It didn't end up really being about Python. See the patch below for details.

**Comment by samfalconer** [comment]
https://supermarket.chef.io/cookbooks/poise-python

... seems like a reasonable way to do it.

**Comment by asmasattar** [comment]
Looks good. Ship 🛳it!

**Comment by samfalconer** [comment]
Merged.
