### ISSUE TITLE
Fix msbuild error so that we can stop force returning 0 from the installation script

### ISSUE THREAD

**Issue by samfalconer** [Tour-de-Force/btc-infrastructure#4]
Currently the install_app Powershell script in nodejs_deploy.rb forces an exit 0 at the end to keep Chef happy. This is needed for https://github.com/Tour-de-Force/btc-infrastructure/issues/1

We should fix the msbuild error or find some way to make npm stop returning a failure error code if an optional dependency failed. I believe it is passing along the nonzero exit code from msbuild.exe

**Comment by samfalconer** [comment]
Merging now to fix the deployment. Leaving open for review.

**Comment by amk5401** [comment]
ship

**Comment by samfalconer** [comment]
Merged. Closing.
